Fix the build of stepcore tests.
It fixes errors such as this one, caused by conflicting types being
passed to Eigen's Matrix constructor.

../stepcore_tests/contacts.cc:121:54: error: call to constructor of 'StepCore::Vector2d' (aka 'Matrix<double, 2, 1>') is ambiguous
            << int(StepCore::Contact::Contacted) << (StepCore::Vector2d(1,1e-5)*9.999999e-04).eval()
                                                     ^                  ~~~~~~
/usr/local/include/eigen2/Eigen/src/Core/Matrix.h:348:25: note: candidate constructor
    EIGEN_STRONG_INLINE Matrix(int x, int y) : m_storage(x*y, x, y)
                        ^
/usr/local/include/eigen2/Eigen/src/Core/Matrix.h:373:25: note: candidate constructor
    EIGEN_STRONG_INLINE Matrix(const double& x, const double& y)
                        ^
/usr/local/include/eigen2/Eigen/src/Core/Matrix.h:365:25: note: candidate constructor
    EIGEN_STRONG_INLINE Matrix(const float& x, const float& y)
                        ^

Submitted by:	Vadim Zukhov <persgray@gmail.com>
REVIEW:		119026